### ISSUE TITLE
[feature request] Support Dead Letter Topic

### ISSUE THREAD

**Issue by BewareMyPower** [apache/pulsar-client-python#107] opened 2023-03-21 14:08 UTC
The C++ client has already implemented the dead letter topic since https://github.com/apache/pulsar-client-cpp/pull/139, which is included in the 3.2.0 release. We should support dead letter topic for Python client.

**Comment by RobertIndie** [comment] 2023-03-22 03:50
This is a duplicate of https://github.com/apache/pulsar-client-python/issues/98

**Closed by RobertIndie** 2023-03-22 03:50 UTC
